--------------------------------------------------------------------------------
-- 30_writeback_ops.sql
-- Sprint 6: Agent-action writeback operations for AGENT_ACTION_WRITEBACK
-- Target: SNOWFLAKE_REVENUE_CC.CORE
-- Called by: Domo Code Engine bridge via Snowflake SQL API
--------------------------------------------------------------------------------

USE ROLE SYSADMIN;
USE WAREHOUSE REVENUE_CC_WH;
USE SCHEMA SNOWFLAKE_REVENUE_CC.CORE;

--------------------------------------------------------------------------------
-- 1. MERGE TEMPLATE — idempotent upsert keyed on ACTION_ID
--    The Code Engine bridge substitutes the literal params below.
--    Params: :ACTION_ID, :ACCOUNT_ID, :ACCOUNT_NAME, :REGION,
--            :RECOMMENDATION, :APPROVAL_STATUS, :APPROVED_BY,
--            :EXECUTION_STATUS, :ACTUAL_REVENUE_PROTECTED, :COMPLETED_TS
--------------------------------------------------------------------------------

MERGE INTO AGENT_ACTION_WRITEBACK tgt
USING (SELECT
  ':ACTION_ID'                          AS ACTION_ID,
  ':ACCOUNT_ID'                         AS ACCOUNT_ID,
  ':ACCOUNT_NAME'                       AS ACCOUNT_NAME,
  ':REGION'                             AS REGION,
  ':RECOMMENDATION'                     AS RECOMMENDATION,
  ':APPROVAL_STATUS'                    AS APPROVAL_STATUS,
  ':APPROVED_BY'                        AS APPROVED_BY,
  ':EXECUTION_STATUS'                   AS EXECUTION_STATUS,
  :ACTUAL_REVENUE_PROTECTED             AS ACTUAL_REVENUE_PROTECTED,
  :COMPLETED_TS                         AS COMPLETED_TS
) src ON tgt.ACTION_ID = src.ACTION_ID
WHEN MATCHED THEN UPDATE SET
  tgt.APPROVAL_STATUS          = src.APPROVAL_STATUS,
  tgt.APPROVED_BY              = src.APPROVED_BY,
  tgt.EXECUTION_STATUS         = src.EXECUTION_STATUS,
  tgt.ACTUAL_REVENUE_PROTECTED = src.ACTUAL_REVENUE_PROTECTED,
  tgt.COMPLETED_TS             = src.COMPLETED_TS
WHEN NOT MATCHED THEN INSERT (
  ACTION_ID, ACCOUNT_ID, ACCOUNT_NAME, REGION, RECOMMENDATION,
  APPROVAL_STATUS, APPROVED_BY, EXECUTION_STATUS,
  ACTUAL_REVENUE_PROTECTED, COMPLETED_TS
) VALUES (
  src.ACTION_ID, src.ACCOUNT_ID, src.ACCOUNT_NAME, src.REGION,
  src.RECOMMENDATION, src.APPROVAL_STATUS, src.APPROVED_BY,
  src.EXECUTION_STATUS, src.ACTUAL_REVENUE_PROTECTED, src.COMPLETED_TS
);

--------------------------------------------------------------------------------
-- 2. GOLD_PROTECTED_REVENUE_ROLLUP — governed view for app consumption
--    Combines baseline (FACT_AGENT_ACTIONS) + live writeback revenue.
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW GOLD_PROTECTED_REVENUE_ROLLUP AS
SELECT
  COALESCE(b.BASELINE_PROTECTED, 0)   AS BASELINE_PROTECTED,
  COALESCE(w.WRITEBACK_PROTECTED, 0)  AS WRITEBACK_PROTECTED,
  COALESCE(b.BASELINE_PROTECTED, 0)
    + COALESCE(w.WRITEBACK_PROTECTED, 0) AS TOTAL_PROTECTED,
  COALESCE(w.WRITEBACK_APPROVED_COUNT, 0) AS WRITEBACK_APPROVED_COUNT,
  COALESCE(w.WRITEBACK_EXECUTED_COUNT, 0) AS WRITEBACK_EXECUTED_COUNT
FROM
  (SELECT SUM(ACTUAL_REVENUE_PROTECTED) AS BASELINE_PROTECTED
   FROM FACT_AGENT_ACTIONS
   WHERE EXECUTION_STATUS IN ('Executed', 'Completed')) b,
  (SELECT
     SUM(CASE WHEN EXECUTION_STATUS = 'Executed'
              THEN ACTUAL_REVENUE_PROTECTED ELSE 0 END) AS WRITEBACK_PROTECTED,
     COUNT(CASE WHEN APPROVAL_STATUS = 'Approved' THEN 1 END) AS WRITEBACK_APPROVED_COUNT,
     COUNT(CASE WHEN EXECUTION_STATUS = 'Executed' THEN 1 END) AS WRITEBACK_EXECUTED_COUNT
   FROM AGENT_ACTION_WRITEBACK) w;

GRANT SELECT ON VIEW GOLD_PROTECTED_REVENUE_ROLLUP TO ROLE REVENUE_CC_READER;

--------------------------------------------------------------------------------
-- 3. VALIDATION (commented — run manually to prove the loop)
--------------------------------------------------------------------------------
/*
-- (a) Approve
MERGE INTO AGENT_ACTION_WRITEBACK tgt
USING (SELECT
  'ACT-0011826' AS ACTION_ID, 'ACC-03221' AS ACCOUNT_ID,
  'Beacon Analytics 3221' AS ACCOUNT_NAME, 'West' AS REGION,
  'Technical success plan' AS RECOMMENDATION,
  'Approved' AS APPROVAL_STATUS,
  'cassidy.hilton@demo.local' AS APPROVED_BY,
  'Pending' AS EXECUTION_STATUS,
  NULL::DOUBLE AS ACTUAL_REVENUE_PROTECTED,
  NULL::TIMESTAMP_NTZ AS COMPLETED_TS
) src ON tgt.ACTION_ID = src.ACTION_ID
WHEN MATCHED THEN UPDATE SET
  tgt.APPROVAL_STATUS = src.APPROVAL_STATUS, tgt.APPROVED_BY = src.APPROVED_BY,
  tgt.EXECUTION_STATUS = src.EXECUTION_STATUS,
  tgt.ACTUAL_REVENUE_PROTECTED = src.ACTUAL_REVENUE_PROTECTED,
  tgt.COMPLETED_TS = src.COMPLETED_TS
WHEN NOT MATCHED THEN INSERT (ACTION_ID, ACCOUNT_ID, ACCOUNT_NAME, REGION, RECOMMENDATION, APPROVAL_STATUS, APPROVED_BY, EXECUTION_STATUS, ACTUAL_REVENUE_PROTECTED, COMPLETED_TS)
VALUES (src.ACTION_ID, src.ACCOUNT_ID, src.ACCOUNT_NAME, src.REGION, src.RECOMMENDATION, src.APPROVAL_STATUS, src.APPROVED_BY, src.EXECUTION_STATUS, src.ACTUAL_REVENUE_PROTECTED, src.COMPLETED_TS);

SELECT * FROM AGENT_ACTION_WRITEBACK WHERE ACTION_ID = 'ACT-0011826';

-- (b) Execute
MERGE INTO AGENT_ACTION_WRITEBACK tgt
USING (SELECT
  'ACT-0011826' AS ACTION_ID, 'ACC-03221' AS ACCOUNT_ID,
  'Beacon Analytics 3221' AS ACCOUNT_NAME, 'West' AS REGION,
  'Technical success plan' AS RECOMMENDATION,
  'Approved' AS APPROVAL_STATUS,
  'cassidy.hilton@demo.local' AS APPROVED_BY,
  'Executed' AS EXECUTION_STATUS,
  207447.8592 AS ACTUAL_REVENUE_PROTECTED,
  CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS COMPLETED_TS
) src ON tgt.ACTION_ID = src.ACTION_ID
WHEN MATCHED THEN UPDATE SET
  tgt.APPROVAL_STATUS = src.APPROVAL_STATUS, tgt.APPROVED_BY = src.APPROVED_BY,
  tgt.EXECUTION_STATUS = src.EXECUTION_STATUS,
  tgt.ACTUAL_REVENUE_PROTECTED = src.ACTUAL_REVENUE_PROTECTED,
  tgt.COMPLETED_TS = src.COMPLETED_TS
WHEN NOT MATCHED THEN INSERT (ACTION_ID, ACCOUNT_ID, ACCOUNT_NAME, REGION, RECOMMENDATION, APPROVAL_STATUS, APPROVED_BY, EXECUTION_STATUS, ACTUAL_REVENUE_PROTECTED, COMPLETED_TS)
VALUES (src.ACTION_ID, src.ACCOUNT_ID, src.ACCOUNT_NAME, src.REGION, src.RECOMMENDATION, src.APPROVAL_STATUS, src.APPROVED_BY, src.EXECUTION_STATUS, src.ACTUAL_REVENUE_PROTECTED, src.COMPLETED_TS);

-- Must be exactly 1 row
SELECT COUNT(*) FROM AGENT_ACTION_WRITEBACK WHERE ACTION_ID = 'ACT-0011826';

-- (c) Rollup should show WRITEBACK_PROTECTED > 0
SELECT * FROM GOLD_PROTECTED_REVENUE_ROLLUP;

-- (d) Cleanup
DELETE FROM AGENT_ACTION_WRITEBACK WHERE ACTION_ID = 'ACT-0011826';
SELECT COUNT(*) FROM AGENT_ACTION_WRITEBACK;  -- expect 0
SELECT * FROM GOLD_PROTECTED_REVENUE_ROLLUP;  -- WRITEBACK_PROTECTED back to 0
*/
