--------------------------------------------------------------------------------
-- 10_roles.sql
-- Sprint 7 Governance: Region-scoped reader roles and mapping table
-- Target: SNOWFLAKE_REVENUE_CC.CORE
--------------------------------------------------------------------------------

-- =============================================================================
-- SECTION 1: Region-scoped reader roles
-- Required executing role: SECURITYADMIN
-- =============================================================================

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS REVENUE_CC_READER_WEST
  COMMENT = 'Region-scoped reader: West region only. Restricted by RAP_REGION and MASK_ARR.';

CREATE ROLE IF NOT EXISTS REVENUE_CC_READER_EAST
  COMMENT = 'Region-scoped reader: East region only. Restricted by RAP_REGION and MASK_ARR.';

-- Warehouse, database, schema usage (mirrors REVENUE_CC_READER)
GRANT USAGE ON WAREHOUSE REVENUE_CC_WH TO ROLE REVENUE_CC_READER_WEST;
GRANT USAGE ON WAREHOUSE REVENUE_CC_WH TO ROLE REVENUE_CC_READER_EAST;
GRANT USAGE ON DATABASE SNOWFLAKE_REVENUE_CC TO ROLE REVENUE_CC_READER_WEST;
GRANT USAGE ON DATABASE SNOWFLAKE_REVENUE_CC TO ROLE REVENUE_CC_READER_EAST;
GRANT USAGE ON SCHEMA SNOWFLAKE_REVENUE_CC.CORE TO ROLE REVENUE_CC_READER_WEST;
GRANT USAGE ON SCHEMA SNOWFLAKE_REVENUE_CC.CORE TO ROLE REVENUE_CC_READER_EAST;

-- SELECT on all current and future tables/views
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE_REVENUE_CC.CORE TO ROLE REVENUE_CC_READER_WEST;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWFLAKE_REVENUE_CC.CORE TO ROLE REVENUE_CC_READER_EAST;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWFLAKE_REVENUE_CC.CORE TO ROLE REVENUE_CC_READER_WEST;
GRANT SELECT ON ALL VIEWS IN SCHEMA SNOWFLAKE_REVENUE_CC.CORE TO ROLE REVENUE_CC_READER_EAST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOWFLAKE_REVENUE_CC.CORE TO ROLE REVENUE_CC_READER_WEST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOWFLAKE_REVENUE_CC.CORE TO ROLE REVENUE_CC_READER_EAST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SNOWFLAKE_REVENUE_CC.CORE TO ROLE REVENUE_CC_READER_WEST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA SNOWFLAKE_REVENUE_CC.CORE TO ROLE REVENUE_CC_READER_EAST;

-- SELECT on semantic view
GRANT SELECT ON SEMANTIC VIEW SNOWFLAKE_REVENUE_CC.CORE.REVENUE_CC_ANALYST TO ROLE REVENUE_CC_READER_WEST;
GRANT SELECT ON SEMANTIC VIEW SNOWFLAKE_REVENUE_CC.CORE.REVENUE_CC_ANALYST TO ROLE REVENUE_CC_READER_EAST;

-- Grant to SYSADMIN hierarchy
GRANT ROLE REVENUE_CC_READER_WEST TO ROLE SYSADMIN;
GRANT ROLE REVENUE_CC_READER_EAST TO ROLE SYSADMIN;

-- Grant to service identity (Code Engine bridge)
-- NOTE: Create user first if it does not exist:
--   USE ROLE USERADMIN;
--   CREATE USER IF NOT EXISTS SVC_REVENUE_CC COMMENT = 'Service identity for Revenue CC' TYPE = SERVICE;
GRANT ROLE REVENUE_CC_READER_WEST TO USER SVC_REVENUE_CC;
GRANT ROLE REVENUE_CC_READER_EAST TO USER SVC_REVENUE_CC;

-- =============================================================================
-- SECTION 2: Governed role->region mapping table
-- Required executing role: SYSADMIN
-- =============================================================================

USE ROLE SYSADMIN;
USE WAREHOUSE REVENUE_CC_WH;
USE SCHEMA SNOWFLAKE_REVENUE_CC.CORE;

CREATE OR REPLACE TABLE GOV_ROLE_REGION_MAP (
  ROLE_NAME VARCHAR(256) NOT NULL,
  REGION    VARCHAR(64)  NOT NULL
);

INSERT INTO GOV_ROLE_REGION_MAP (ROLE_NAME, REGION) VALUES
  ('REVENUE_CC_READER_WEST', 'West'),
  ('REVENUE_CC_READER_EAST', 'East');
