--------------------------------------------------------------------------------
-- 10_knowledge_docs.sql
-- Creates and populates KNOWLEDGE_DOCS: unstructured corpus for Cortex Search.
-- Target: SNOWFLAKE_REVENUE_CC.CORE
--------------------------------------------------------------------------------

CREATE OR REPLACE TABLE SNOWFLAKE_REVENUE_CC.CORE.KNOWLEDGE_DOCS (
    DOC_ID      STRING      NOT NULL PRIMARY KEY,
    DOC_TYPE    STRING      NOT NULL,
    TITLE       STRING      NOT NULL,
    REGION      STRING      NOT NULL,
    SEGMENT     STRING      NOT NULL,
    ACCOUNT_NAME STRING     NOT NULL,
    SOURCE_DATE DATE        NOT NULL,
    BODY        TEXT        NOT NULL
);

INSERT INTO SNOWFLAKE_REVENUE_CC.CORE.KNOWLEDGE_DOCS
    (DOC_ID, DOC_TYPE, TITLE, REGION, SEGMENT, ACCOUNT_NAME, SOURCE_DATE, BODY)
VALUES
-- ============================================================================
-- INCIDENT POSTMORTEMS
-- ============================================================================
('DOC-001', 'Incident Postmortem', 'INC-0001 Post-Incident Review: West Region Platform Reliability Degradation', 'West', 'Enterprise', 'Acme Financial Services',
 '2026-06-02',
 'Incident INC-0001 was declared on 2026-05-28 at 14:32 UTC when monitoring detected sustained p99 latency spikes exceeding 4500ms on the West region primary compute cluster. The root cause was traced to a cascading failure in the storage tier triggered by a firmware bug in NVMe controllers affecting rack W-14 through W-19. Duration: 6 hours 47 minutes. During this window, 241 Enterprise accounts in the West region experienced query failures, timeout errors, and data pipeline stalls. SLA breach notifications were issued to all affected accounts whose monthly uptime dropped below the contractual 99.95% threshold. Acme Financial Services, our largest West Enterprise account ($4.2M ARR), reported complete inability to run their end-of-month regulatory reporting suite during the incident window. Remediation included emergency firmware patching, failover to secondary storage pools, and proactive customer outreach. Post-incident analysis shows this single event accounts for 73% of all SLA breaches recorded in the West region for May 2026. Renewal risk scoring models now flag 241 West Enterprise accounts at elevated risk (avg score 83/100) directly attributable to INC-0001 impact.'),

('DOC-002', 'Incident Postmortem', 'INC-0001 Customer Impact Assessment: West Enterprise Cohort', 'West', 'Enterprise', 'Pacific Mutual Insurance',
 '2026-06-04',
 'This document details the customer impact of INC-0001 across the West Enterprise segment. Of 312 total West Enterprise accounts, 241 (77%) experienced measurable service degradation during the 6h47m incident window. Impact severity breakdown: 89 accounts experienced complete service unavailability (Severity 1), 112 accounts experienced partial degradation with >50% query failure rate (Severity 2), and 40 accounts experienced intermittent errors (Severity 3). Pacific Mutual Insurance reported that their real-time claims processing pipeline was offline for the full duration, resulting in a backlog of 14,000 claims requiring manual intervention. SLA credits estimated at $2.1M across all affected accounts. The renewal risk model has been updated: accounts with Severity 1 impact now carry an average renewal risk score of 91, Severity 2 averages 83, and Severity 3 averages 72. Key accounts flagged for immediate executive outreach include Acme Financial Services, Pacific Mutual Insurance, Western Digital Analytics, TechNova Solutions, and Cascade Health Systems.'),

('DOC-003', 'Incident Postmortem', 'INC-0001 Root Cause Analysis and Prevention Plan', 'West', 'Enterprise', 'Western Digital Analytics',
 '2026-06-05',
 'Root Cause: INC-0001 originated from a known firmware defect (CVE-2026-3847) in Vendor X NVMe controllers deployed in racks W-14 through W-19. The defect causes controller lockup under sustained high-IOPS workloads when drive temperature exceeds 72C. Contributing factors: (1) Cooling system maintenance window overlapped with peak workload period, raising ambient rack temperature by 4C. (2) Firmware patch had been staged but not yet deployed due to change-freeze policy during month-end processing. (3) Blast radius was amplified because rack affinity rules placed multiple large Enterprise tenants on adjacent racks. Prevention measures implemented: immediate firmware deployment to all affected controllers, revised change-freeze exemption policy for critical security/reliability patches, rack diversity requirement for accounts >$1M ARR, enhanced thermal monitoring with automated workload migration at 68C threshold. Western Digital Analytics lost 4 hours of ETL processing and has formally requested a reliability roadmap review before their August renewal.'),

('DOC-004', 'Incident Postmortem', 'INC-0001 Timeline and Communications Log', 'West', 'Enterprise', 'TechNova Solutions',
 '2026-06-03',
 'INC-0001 Detailed Timeline: 14:32 UTC - Automated alert fires for p99 latency >4000ms on West compute cluster. 14:38 - On-call SRE acknowledges, begins investigation. 14:52 - Severity escalated to SEV-1 after confirming widespread query failures across multiple tenants. 15:05 - Customer-facing status page updated. 15:15 - First batch of SLA breach notifications sent to 89 accounts with complete unavailability. 15:45 - Root cause identified as NVMe controller lockup on racks W-14 to W-19. 16:20 - Emergency failover initiated to secondary storage pools. 18:30 - Partial service restoration for Severity 2 and 3 accounts. 20:45 - Full service restoration confirmed. 21:19 - Incident formally closed. TechNova Solutions ($2.8M ARR) contacted their account executive during the incident to express serious concern about platform reliability ahead of their Q3 renewal decision. Their CTO stated they are evaluating alternative providers if another incident of this magnitude occurs within 90 days.'),

-- ============================================================================
-- SUPPORT CASE NOTES
-- ============================================================================
('DOC-010', 'Support Case Note', 'CASE-88712: Acme Financial Services - Query Timeout Escalation Post INC-0001', 'West', 'Enterprise', 'Acme Financial Services',
 '2026-06-03',
 'Customer: Acme Financial Services. Case opened by VP of Data Engineering. Issue: Following INC-0001, customer reports continued intermittent query timeouts on large aggregation workloads (>500GB scan). Customer states their confidence in platform reliability has been severely impacted. They are requesting: (1) detailed written SLA compliance report for the past 90 days, (2) confirmation of remediation steps taken, (3) meeting with engineering leadership to review reliability roadmap. Customer explicitly mentioned renewal risk, stating "we need to see a credible path to improved reliability before we can commit to a 3-year renewal in August." Current contract: $4.2M ARR, renewal date 2026-08-15. Account health: RED. Renewal risk score: 94/100.'),

('DOC-011', 'Support Case Note', 'CASE-88745: Pacific Mutual Insurance - SLA Credit Request and Performance Concerns', 'West', 'Enterprise', 'Pacific Mutual Insurance',
 '2026-06-04',
 'Customer: Pacific Mutual Insurance. Case opened by CIO office. Issue: Formal SLA credit request for May 2026 downtime during INC-0001. Customer calculates 99.87% uptime for May vs contractual 99.95%, requesting $340K credit. Additionally, customer reports that since INC-0001, they have observed 2-3x longer query compilation times during peak hours (8-10am PT). Engineering investigation shows this is unrelated to INC-0001 (workload growth pattern) but customer perception ties all performance issues to the incident. Customer stated on call: "Every slow query now makes us wonder if another outage is coming. Our board is asking about our cloud vendor concentration risk." Contract: $3.1M ARR, renewal date 2026-09-30. Renewal risk score: 87/100.'),

('DOC-012', 'Support Case Note', 'CASE-88801: TechNova Solutions - Reliability Guarantee Request', 'West', 'Enterprise', 'TechNova Solutions',
 '2026-06-06',
 'Customer: TechNova Solutions. Case opened by CTO directly to account executive. Issue: Customer requesting enhanced SLA terms for renewal - specifically 99.99% uptime guarantee with 10x credit multiplier for breaches, citing INC-0001 as justification. Customer has received competitive proposals from two alternative providers offering 99.99% SLAs with migration support packages. TechNova runs mission-critical fraud detection pipelines that cannot tolerate >5 minutes of downtime. During INC-0001, they experienced 3 hours of complete unavailability resulting in $890K of unprocessed transactions that required manual review. Account executive notes: "This is our most at-risk Enterprise renewal in West. Without a compelling reliability commitment and executive engagement, probability of churn is >60%." Contract: $2.8M ARR, renewal date 2026-07-31. Renewal risk score: 92/100.'),

('DOC-013', 'Support Case Note', 'CASE-88834: Cascade Health Systems - Data Pipeline Recovery Issues', 'West', 'Enterprise', 'Cascade Health Systems',
 '2026-06-07',
 'Customer: Cascade Health Systems. Case opened by Director of Analytics. Issue: While INC-0001 service was restored, customer reports that 3 of their 12 Snowpipe ingestion streams failed to auto-resume after the incident. Manual intervention was required to restart these streams, resulting in an additional 8 hours of data lag beyond the incident window. Customer concerned about data completeness for their CMS regulatory submission due 2026-06-15. Customer requests: (1) root cause for stream non-recovery, (2) assurance that auto-recovery mechanisms will function in future incidents, (3) executive sponsor meeting to discuss overall platform reliability. Contract: $1.9M ARR, renewal 2026-10-15. Renewal risk: 78/100. Note: This account was previously GREEN health; INC-0001 has moved them to YELLOW.'),

('DOC-014', 'Support Case Note', 'CASE-88856: Western Digital Analytics - ETL Failure Compensation', 'West', 'Enterprise', 'Western Digital Analytics',
 '2026-06-08',
 'Customer: Western Digital Analytics. Case opened by Head of Data Platform. Issue: INC-0001 caused complete failure of their nightly ETL pipeline, resulting in 4 hours of data unavailability for downstream BI dashboards used by 2,000+ business users. Customer is requesting SLA credits of $180K plus a formal written commitment that their workloads will be migrated to isolated compute resources before their August renewal. Customer CTO has scheduled a call with our VP Engineering for 2026-06-12 to discuss reliability roadmap. Customer stated: "We selected this platform for reliability. INC-0001 fundamentally challenges that value proposition. We need concrete evidence that this cannot recur before we renew." Contract: $2.4M ARR, renewal 2026-08-31. Renewal risk score: 85/100.'),

('DOC-015', 'Support Case Note', 'CASE-88902: Sierra Manufacturing - Intermittent Connectivity Post-Incident', 'West', 'Enterprise', 'Sierra Manufacturing',
 '2026-06-09',
 'Customer: Sierra Manufacturing. Case opened by IT Director. Issue: Customer reports sporadic connection drops (2-3 per day) since INC-0001. Engineering investigation confirms these are unrelated to the incident (traced to customer-side network configuration change made during their own incident response). However, customer perception remains that platform stability has degraded. Account team notes heightened sensitivity to any performance anomaly. Recommended approach: proactive outreach with detailed telemetry showing current platform stability metrics. Contract: $1.4M ARR, renewal 2026-11-30. Renewal risk score: 71/100. Risk driver: perception of reliability decline post INC-0001, even though current issues are customer-side.'),

('DOC-016', 'Support Case Note', 'CASE-88934: Velocity Logistics - Missed SLA Penalty Clause Triggered', 'West', 'Enterprise', 'Velocity Logistics',
 '2026-06-10',
 'Customer: Velocity Logistics. Case escalated by Legal/Procurement. Issue: Customer contract contains non-standard penalty clause: any month with <99.9% uptime triggers automatic 15% discount on next renewal term. INC-0001 brought May uptime to 99.87%. Customer legal team has formally notified us that the penalty clause is triggered and they expect the discount applied to their October renewal. This represents ~$375K annual revenue reduction on their $2.5M contract. Account team exploring whether service credits can satisfy the penalty clause instead. Renewal risk: 79/100, but financial impact is confirmed regardless of renewal outcome.'),

('DOC-017', 'Support Case Note', 'CASE-88967: Pinnacle Biotech - Compliance Audit Concerns', 'West', 'Enterprise', 'Pinnacle Biotech',
 '2026-06-11',
 'Customer: Pinnacle Biotech. Case opened by Chief Compliance Officer. Issue: INC-0001 downtime occurred during an active FDA audit window. Customer was unable to produce required data exports for 3 audit queries during the incident. While the audit team granted a 48-hour extension, customer states this created reputational risk with their regulator. They are requesting: (1) formal incident documentation suitable for regulatory filing, (2) enhanced SLA with specific compliance-workload guarantees, (3) dedicated support contact for future audit windows. Customer indicated that platform reliability is now a board-level discussion topic for their upcoming renewal. Contract: $1.7M ARR, renewal 2026-09-15. Renewal risk: 81/100.'),

('DOC-018', 'Support Case Note', 'CASE-89001: Summit Analytics Group - Performance Degradation Report', 'West', 'Enterprise', 'Summit Analytics Group',
 '2026-06-12',
 'Customer: Summit Analytics Group. Case opened by VP Engineering. Issue: Customer reports 40% increase in average query latency for their top-20 most-executed queries comparing the week before INC-0001 to the week after. Engineering review confirms a 12% latency increase attributable to temporary storage rebalancing performed as part of INC-0001 remediation, expected to normalize within 2 weeks. Remaining 28% increase is due to customer workload growth (new data sources onboarded). Customer is conflating both issues with INC-0001 impact. Recommended: schedule technical deep-dive with customer engineering team to separate incident impact from organic growth. Contract: $2.1M ARR, renewal 2026-08-20. Renewal risk: 80/100.'),

('DOC-019', 'Support Case Note', 'CASE-89045: NovaPay Financial - Transaction Processing SLA Breach', 'West', 'Enterprise', 'NovaPay Financial',
 '2026-06-13',
 'Customer: NovaPay Financial. Case opened by COO. Issue: During INC-0001, their real-time transaction scoring pipeline was unavailable for 4 hours 23 minutes. Per their contract addendum, transaction processing workloads carry a 99.99% SLA (stricter than standard). Breach penalty: $50K per hour of downtime beyond 5 minutes = $215K credit owed. Customer states this is the first SLA breach in 3 years of partnership and while they remain committed to the platform, they require: (1) immediate credit issuance, (2) dedicated infrastructure isolation for their transaction workloads, (3) quarterly reliability review cadence. Contract: $3.6M ARR, renewal 2026-07-15. Renewal risk: 76/100 (lower than peers due to strong relationship, but financially impactful).'),

('DOC-020', 'Support Case Note', 'CASE-89112: Redwood Capital Management - Data Integrity Concerns', 'West', 'Enterprise', 'Redwood Capital Management',
 '2026-06-14',
 'Customer: Redwood Capital Management. Case opened by Head of Quantitative Research. Issue: Customer ran data integrity checks after INC-0001 and found 47 rows in a critical pricing table with NULL values where data should exist. Investigation shows these NULLs pre-date the incident (data quality issue in upstream feed), but customer initially attributed them to the outage. After joint investigation, customer acknowledged the NULLs are pre-existing, but expressed concern: "If we cannot trust the platform during an outage, how do we verify nothing was corrupted?" Requesting formal data integrity attestation for all tables modified during the incident window. Contract: $2.9M ARR, renewal 2026-09-01. Renewal risk: 74/100.'),

-- East region support cases for realism
('DOC-021', 'Support Case Note', 'CASE-89200: Atlantic Commerce Group - Warehouse Scaling Optimization', 'East', 'Enterprise', 'Atlantic Commerce Group',
 '2026-06-10',
 'Customer: Atlantic Commerce Group. Case opened by Data Platform Manager. Issue: Routine performance optimization request. Customer experiencing longer-than-expected queue times during their 9-11am peak window. Recommended multi-cluster warehouse configuration with min 2 / max 6 clusters. Customer approved change, implemented same day. No reliability concerns. Account health: GREEN. Renewal risk: 23/100. Contract: $1.8M ARR, renewal 2026-12-01.'),

('DOC-022', 'Support Case Note', 'CASE-89234: Northeastern Healthcare Alliance - Data Sharing Setup', 'East', 'Enterprise', 'Northeastern Healthcare Alliance',
 '2026-06-12',
 'Customer: Northeastern Healthcare Alliance. Case opened by Director of Interoperability. Issue: Customer requesting assistance setting up secure data sharing with 3 partner hospital systems. Standard implementation engagement, no platform concerns. Customer praised platform stability and ease of data sharing configuration. Account health: GREEN. Renewal risk: 18/100. Contract: $2.2M ARR, renewal 2026-11-15.'),

-- Central support case
('DOC-023', 'Support Case Note', 'CASE-89267: MidStates Energy Corp - Cost Optimization Review', 'Central', 'Enterprise', 'MidStates Energy Corp',
 '2026-06-11',
 'Customer: MidStates Energy Corp. Case opened by CFO office. Issue: Quarterly cost review - customer spend increased 35% QoQ due to new IoT data ingestion workloads. Requesting guidance on cost optimization strategies. Recommended: (1) switch to auto-suspend with 60s timeout, (2) implement resource monitors, (3) evaluate materialized views for repeated aggregation queries. No reliability concerns. Account health: GREEN. Renewal risk: 31/100 (cost sensitivity only). Contract: $1.5M ARR, renewal 2026-10-01.'),

-- Mid-Market/SMB for diversity
('DOC-024', 'Support Case Note', 'CASE-89301: QuickServe Analytics - Login Issues', 'West', 'Mid-Market', 'QuickServe Analytics',
 '2026-06-08',
 'Customer: QuickServe Analytics. Case opened by admin user. Issue: MFA configuration issue preventing 2 users from logging in after password reset. Standard SSO troubleshooting, resolved in 30 minutes. No relation to INC-0001. Account health: GREEN. Renewal risk: 15/100. Contract: $120K ARR, renewal 2026-09-01.'),

('DOC-025', 'Support Case Note', 'CASE-89345: DataDash SMB - Billing Question', 'South', 'SMB', 'DataDash SMB',
 '2026-06-09',
 'Customer: DataDash SMB. Case opened by account owner. Issue: Question about compute credit consumption on their on-demand plan. Explained credit billing model and recommended pre-purchasing capacity for 20% savings. No technical issues. Account health: GREEN. Renewal risk: 10/100. Contract: $24K ARR, monthly.'),

-- ============================================================================
-- QBR CALL SUMMARIES
-- ============================================================================
('DOC-030', 'QBR Call Summary', 'Q2 QBR: Acme Financial Services - Renewal Risk Discussion', 'West', 'Enterprise', 'Acme Financial Services',
 '2026-06-15',
 'Q2 2026 QBR with Acme Financial Services. Attendees: Customer - CFO, VP Data Engineering, Head of Procurement; Internal - Account Executive, Customer Success Manager, VP Engineering. Key discussion points: (1) INC-0001 impact review: Customer reiterated that the 6h47m outage caused material business disruption to regulatory reporting. CFO stated: "Our board has asked me to present cloud vendor risk assessment at the July meeting. I need ammunition to justify continued investment." (2) SLA credit: $520K credit approved and applied. (3) Renewal discussion: Current contract expires 2026-08-15 at $4.2M ARR. Customer indicated they will not sign a 3-year term without: (a) enhanced SLA of 99.99% with meaningful penalties, (b) dedicated infrastructure option, (c) executive-level reliability review quarterly. (4) Competitive pressure: Customer confirmed receiving proposals from two competitors. VP Engineering presented reliability roadmap including rack diversity, enhanced monitoring, and sub-5-minute failover target. Customer response: "Directionally positive but we need to see execution, not just plans." Renewal probability assessed at 55% for 3-year, 75% for 1-year at current terms. Revenue at risk: $4.2M.'),

('DOC-031', 'QBR Call Summary', 'Q2 QBR: TechNova Solutions - Churn Prevention Escalation', 'West', 'Enterprise', 'TechNova Solutions',
 '2026-06-14',
 'Q2 2026 QBR with TechNova Solutions. Attendees: Customer - CTO, VP Platform Engineering, Procurement Lead; Internal - Account Executive, Customer Success Director, Sr. Solutions Architect. Critical account status: HIGH CHURN RISK. Key points: (1) CTO opened by stating: "I have two signed proposals on my desk from competitors. The only reason I am in this meeting is the switching cost. Give me a reason to stay." (2) INC-0001 impact: 3 hours of complete unavailability for fraud detection pipeline, $890K unprocessed transactions. Customer states this is unacceptable for their use case. (3) Demands for renewal: 99.99% SLA, dedicated compute isolation, 24/7 premium support with 5-minute response time, and 25% price reduction to offset "risk premium." (4) Competitive landscape: Customer showed live demo of competitor environment they have been testing for 6 weeks. (5) Action items: Executive escalation to our CRO, custom reliability proposal within 5 business days, dedicated SE assigned full-time for 90 days. Renewal probability: 35%. Revenue at risk: $2.8M ARR. Renewal date: 2026-07-31 (IMMINENT).'),

('DOC-032', 'QBR Call Summary', 'Q2 QBR: Pacific Mutual Insurance - Confidence Rebuilding', 'West', 'Enterprise', 'Pacific Mutual Insurance',
 '2026-06-16',
 'Q2 2026 QBR with Pacific Mutual Insurance. Attendees: Customer - CIO, SVP Claims Technology, Vendor Management Director; Internal - Account Executive, Customer Success Manager, Engineering Director. Tone: concerned but constructive. Key discussion: (1) INC-0001 impact: 14,000 claims processing backlog, full recovery took 36 hours including data reconciliation. CIO stated: "We have invested heavily in this platform. We want to stay but our board is asking hard questions about single-vendor risk." (2) SLA credit: $340K credit request approved. (3) Positive signals: Customer acknowledged our transparent communication during incident and rapid post-incident follow-up. CIO: "Your response after the fact has been excellent. The question is prevention, not response." (4) Renewal positioning: Customer open to renewal if we deliver: enhanced monitoring dashboard with real-time SLA tracking, quarterly executive reliability reviews, and priority placement on new infrastructure when available. (5) Next steps: Technical deep-dive on new rack diversity architecture scheduled for 2026-06-25. Renewal probability: 70%. Contract: $3.1M ARR, renewal 2026-09-30.'),

('DOC-033', 'QBR Call Summary', 'Q2 QBR: Western Digital Analytics - Reliability Roadmap Review', 'West', 'Enterprise', 'Western Digital Analytics',
 '2026-06-18',
 'Q2 2026 QBR with Western Digital Analytics. Attendees: Customer - CTO, Director of Data Platform, Sr. Data Engineer; Internal - Account Executive, Solutions Architect, Sr. SRE. Meeting focus: Technical deep-dive on reliability improvements post INC-0001. Key outcomes: (1) Presented new architecture: multi-AZ storage with synchronous replication, automated failover <2 minutes, rack diversity for accounts >$1M ARR. Customer CTO reaction: "This is what we expected from day one. Why did it take an outage to get here?" (2) Customer requested timeline commitments: multi-AZ by end of Q3, automated failover by end of Q4. We committed to Q3 for multi-AZ, Q4 target for failover. (3) Renewal discussion: Customer stated they will renew if (a) multi-AZ is delivered before their Aug 31 renewal date and their workloads are migrated, (b) SLA credits for INC-0001 ($180K) are applied immediately. (4) Expansion opportunity: if reliability is proven, customer has $800K expansion pipeline for new ML workloads. Renewal probability: 65%. Contract: $2.4M ARR.'),

('DOC-034', 'QBR Call Summary', 'Q2 QBR: Cascade Health Systems - Regulatory Compliance Focus', 'West', 'Enterprise', 'Cascade Health Systems',
 '2026-06-17',
 'Q2 2026 QBR with Cascade Health Systems. Attendees: Customer - CISO, Director of Analytics, Compliance Manager; Internal - Account Executive, Customer Success Manager, Security Architect. Key themes: (1) INC-0001 impact on compliance posture: Customer has upcoming HIPAA audit in August. They need documentation proving data integrity was maintained during the incident. Our engineering team provided formal attestation that no data corruption occurred. (2) Snowpipe recovery issue (CASE-88834): Customer satisfied with root cause explanation but requesting automated alerting when streams fail to resume. Feature request logged. (3) Renewal sentiment: Customer is pragmatic - switching costs in healthcare are extremely high. They will renew but are requesting enhanced compliance-specific SLA addendum. (4) Renewal risk driven primarily by procurement seeking 10% discount citing INC-0001 as leverage. Renewal probability: 85%. Revenue at risk: $1.9M ARR (potential 10% discount = $190K reduction).'),

('DOC-035', 'QBR Call Summary', 'Q2 QBR: Atlantic Commerce Group - Growth Discussion', 'East', 'Enterprise', 'Atlantic Commerce Group',
 '2026-06-20',
 'Q2 2026 QBR with Atlantic Commerce Group. Attendees: Customer - VP Data, Platform Architect; Internal - Account Executive, Solutions Architect. Extremely positive meeting. Customer praised platform stability (unaffected by INC-0001 as they are in East region). Key topics: (1) 45% YoY data growth, planning to expand from 2 to 5 warehouses. (2) Interested in new ML features for demand forecasting. (3) Renewal: early renewal discussion for December - customer interested in 3-year commit for volume pricing. No churn risk. Expansion pipeline: $600K. Account health: GREEN.'),

('DOC-036', 'QBR Call Summary', 'Q2 QBR: NovaPay Financial - Transaction SLA Remediation', 'West', 'Enterprise', 'NovaPay Financial',
 '2026-06-19',
 'Q2 2026 QBR with NovaPay Financial. Attendees: Customer - COO, VP Engineering, Legal Counsel; Internal - Account Executive, VP Customer Success, Engineering Director. Focus: remediation plan for transaction processing SLA breach during INC-0001. Key outcomes: (1) $215K SLA credit approved per contract terms. (2) Customer COO stated: "We have a strong 3-year partnership. One incident does not define a relationship, but the response to it does. Show us this cannot happen again." (3) Agreed deliverables: dedicated compute cluster for transaction workloads by July 1, real-time failover testing every 30 days with customer observation, enhanced monitoring with customer-visible dashboard. (4) Renewal: July 15 renewal date approaching. Customer will renew if dedicated compute is operational by then. Verbal commitment received. Renewal probability: 80%. Contract: $3.6M ARR.'),

('DOC-037', 'QBR Call Summary', 'Q2 QBR: Pinnacle Biotech - Audit Preparedness', 'West', 'Enterprise', 'Pinnacle Biotech',
 '2026-06-21',
 'Q2 2026 QBR with Pinnacle Biotech. Attendees: Customer - Chief Compliance Officer, Head of Data Science, Procurement; Internal - Account Executive, Customer Success Manager, Compliance Specialist. Key points: (1) INC-0001 FDA audit impact resolved - regulator accepted our formal incident documentation. Customer relieved but CCO stated: "We got lucky with the extension. If this happens during our November submission window, the consequences are severe." (2) Customer requesting: audit-window protection (guaranteed no maintenance during declared audit periods), enhanced SLA for compliance workloads, formal DR testing participation. (3) Renewal: September 15 date. Customer will renew but seeking enhanced compliance terms. Procurement using INC-0001 as negotiation leverage for 12% discount. Renewal probability: 78%. Revenue impact: potential $204K discount on $1.7M ARR.'),

-- ============================================================================
-- RENEWAL PLAYBOOKS
-- ============================================================================
('DOC-040', 'Renewal Playbook', 'Save Play: Executive Escalation Protocol for At-Risk Enterprise Accounts', 'West', 'Enterprise', 'ALL ACCOUNTS',
 '2026-06-05',
 'RENEWAL PLAYBOOK: Executive Escalation Protocol. Applicability: Any Enterprise account with renewal risk score >75 and ARR >$1.5M. Triggered by: INC-0001 impact, SLA breach, or competitive threat. Step 1 - Executive Sponsor Assignment: Within 48 hours of risk identification, assign a VP or C-level executive sponsor. For accounts >$3M ARR, CRO personal involvement required. Step 2 - Outreach Cadence: Executive sponsor calls customer C-suite within 5 business days. Acknowledge impact directly and personally. Do not delegate to account team. Step 3 - Listening Session: First call is 80% listening. Document customer concerns, business impact, and specific requirements for continued partnership. Step 4 - Custom Proposal: Within 10 business days, deliver a written proposal addressing each customer concern with specific commitments, timelines, and accountability. Step 5 - Follow-through: Weekly executive check-ins until renewal is secured. Measure: NPS at each touchpoint. Success criteria: Renewal signed within 30 days of proposal delivery.'),

('DOC-041', 'Renewal Playbook', 'Save Play: Service Credit and Commercial Concession Framework', 'West', 'Enterprise', 'ALL ACCOUNTS',
 '2026-06-06',
 'RENEWAL PLAYBOOK: Service Credit and Commercial Concessions. Context: Following INC-0001, multiple West Enterprise accounts are requesting credits and concessions. This playbook defines the approved framework. Tier 1 (Severity 1 impact, >$3M ARR): Up to 15% of monthly charges as credit, plus up to 5% renewal discount, plus enhanced SLA terms at no additional cost. Tier 2 (Severity 2 impact, $1.5M-$3M ARR): Up to 10% of monthly charges as credit, plus up to 3% renewal discount. Tier 3 (Severity 3 impact or <$1.5M ARR): Standard SLA credit per contract terms, no additional discount. Additional levers: (a) Extended payment terms (Net-60 to Net-90), (b) Free tier upgrade for 6 months, (c) Dedicated support engineer for 90 days at no cost, (d) Free professional services engagement (up to 40 hours). Approval authority: Tier 1 requires CRO approval, Tier 2 requires VP Sales approval, Tier 3 can be approved by Regional Director. Total INC-0001 credit exposure estimated at $2.1M across all affected accounts.'),

('DOC-042', 'Renewal Playbook', 'Save Play: Reliability Roadmap Review - Customer Presentation Template', 'West', 'Enterprise', 'ALL ACCOUNTS',
 '2026-06-07',
 'RENEWAL PLAYBOOK: Reliability Roadmap Customer Presentation. Purpose: Rebuild customer confidence by demonstrating concrete reliability investments post INC-0001. Target audience: Technical decision-makers (CTO, VP Eng) at West Enterprise accounts with renewal risk >70. Presentation structure: (1) Acknowledgment: "We fell short of your expectations. Here is exactly what happened and what we are doing about it." (2) Root Cause Transparency: Full technical explanation of INC-0001 (firmware defect, thermal conditions, blast radius). Customers respect honesty. (3) Immediate Actions Taken (completed): firmware patching, enhanced monitoring, thermal safeguards. (4) 30-Day Deliverables: rack diversity for all >$1M accounts, automated failover testing, customer-visible reliability dashboard. (5) 90-Day Deliverables: multi-AZ storage with synchronous replication, sub-2-minute failover, enhanced SLA options. (6) 180-Day Vision: zero-downtime architecture, chaos engineering program, customer reliability advisory board. Key message: "We are investing $XX million in reliability. You will see measurable improvement within 30 days." Customize dollar amount per customer tier.'),

('DOC-043', 'Renewal Playbook', 'Save Play: Success Plan Reset for Post-Incident Recovery', 'West', 'Enterprise', 'ALL ACCOUNTS',
 '2026-06-08',
 'RENEWAL PLAYBOOK: Success Plan Reset. When to use: After a major incident (like INC-0001) has damaged the customer relationship, the existing success plan is no longer aligned with customer priorities. A reset demonstrates responsiveness and customer-centricity. Process: (1) Acknowledge that previous success metrics and goals need revision in light of the incident. (2) Schedule a dedicated success plan reset session (separate from QBR) within 2 weeks of incident. (3) Co-create new success criteria with customer input. Common post-incident success metrics: uptime measurement (customer-visible dashboard), recovery time objective (RTO) demonstration, proactive communication cadence, quarterly reliability reviews. (4) Assign dedicated Customer Success Engineer (CSE) for 90 days - not a new person, but elevated engagement from existing CSE. (5) Weekly progress reports against new success plan for first 60 days, then biweekly. (6) 90-day checkpoint: formal review of whether confidence has been rebuilt. If not, escalate to executive team. (7) Document all commitments in writing with customer sign-off. Expected outcome: transform incident damage into deeper partnership through demonstrated accountability.'),

('DOC-044', 'Renewal Playbook', 'Save Play: Competitive Displacement Defense for West Enterprise', 'West', 'Enterprise', 'ALL ACCOUNTS',
 '2026-06-10',
 'RENEWAL PLAYBOOK: Competitive Displacement Defense. Context: Following INC-0001, at least 4 West Enterprise accounts have confirmed receiving or soliciting competitive proposals. This playbook provides defense strategies. Intelligence gathering: (1) Identify which competitors are engaged (signals: customer mentions specific features, asks about data portability, reduces consumption). (2) Assess switching barriers: data volume (>100TB = high barrier), custom integrations, trained users, embedded workflows. (3) Map customer decision timeline against renewal date. Defense tactics: (a) Total cost of migration analysis - present realistic migration costs including downtime, retraining, and integration rebuild. (b) Feature gap analysis vs competitor - highlight capabilities competitor lacks. (c) Acceleration offer - bring forward roadmap items that address customer concerns. (d) Executive alignment - match or exceed competitor executive engagement level. (e) Proof of improvement - offer free 30-day enhanced monitoring showing reliability improvements since INC-0001. Red flags requiring immediate CRO escalation: customer requests data export in bulk, reduces workload volume >20%, refuses meetings, or mentions specific competitor migration timeline.'),

('DOC-045', 'Renewal Playbook', 'Save Play: Multi-Year Commitment Incentive for At-Risk Renewals', 'West', 'Enterprise', 'ALL ACCOUNTS',
 '2026-06-12',
 'RENEWAL PLAYBOOK: Multi-Year Commitment Incentive. Applicability: West Enterprise accounts considering churn due to INC-0001 where relationship is salvageable (renewal probability >40%). Strategy: Convert flight risk into long-term commitment by offering compelling multi-year economics. Offer structure: (a) 1-year renewal at current rates with enhanced SLA: minimal incentive, signals lack of confidence in own platform. Not recommended. (b) 2-year renewal: 8% discount + enhanced SLA + dedicated support + quarterly executive reviews. Recommended for accounts with renewal risk 70-80. (c) 3-year renewal: 12% discount + premium SLA (99.99%) + dedicated compute option + named executive sponsor + annual innovation workshop. Recommended for accounts with renewal risk >80 where switching cost is high. Break-even analysis: 12% discount on a $3M account = $360K/year reduction. Cost of acquisition for replacement revenue = 18-24 months of effort. Multi-year lock-in provides $5.28M guaranteed vs risk of $0. Always present total contract value to customer to anchor on commitment size.'),

-- ============================================================================
-- EXEC ESCALATIONS
-- ============================================================================
('DOC-050', 'Exec Escalation', 'ESCALATION: TechNova Solutions - CRO Direct Engagement Required', 'West', 'Enterprise', 'TechNova Solutions',
 '2026-06-15',
 'EXECUTIVE ESCALATION - URGENT. Account: TechNova Solutions. ARR: $2.8M. Renewal Date: 2026-07-31 (46 days). Escalation Reason: Account at imminent churn risk following INC-0001. CTO has competitive proposals and is actively testing alternative platform. Required Action: CRO direct engagement within 48 hours. Background: TechNova runs mission-critical fraud detection on our platform. INC-0001 caused 3 hours of unavailability, resulting in $890K of unprocessed transactions. CTO stated in QBR: "I have two signed proposals on my desk." Customer demands: 99.99% SLA, dedicated compute, 24/7 premium support, 25% price reduction. Recommended CRO approach: (1) Personal call acknowledging failure and committing to specific reliability guarantees. (2) Offer dedicated compute cluster at no additional cost for 12 months. (3) Enhanced SLA with meaningful penalties demonstrating skin in the game. (4) Dedicated SE for 90 days. (5) Innovation partnership: early access to new features. Do NOT offer price reduction as first lever - compete on value and commitment. Revenue at risk: $2.8M ARR. Probability of save with CRO engagement: 55%. Without: 20%.'),

('DOC-051', 'Exec Escalation', 'ESCALATION: Acme Financial Services - VP Sales West + VP Engineering Joint Response', 'West', 'Enterprise', 'Acme Financial Services',
 '2026-06-12',
 'EXECUTIVE ESCALATION. Account: Acme Financial Services. ARR: $4.2M (largest West Enterprise account). Renewal Date: 2026-08-15 (64 days). Escalation Reason: CFO explicitly stated renewal risk in QBR. Board-level cloud vendor review scheduled for July. Required Action: Joint response from VP Sales West and VP Engineering within 5 business days. Background: INC-0001 caused 6h47m of complete unavailability during month-end regulatory reporting. $520K SLA credit already applied. Customer requesting: enhanced SLA (99.99%), dedicated infrastructure, quarterly executive reliability reviews. CFO quote: "I need ammunition to justify continued investment at our board meeting." Recommended approach: (1) VP Engineering to present reliability roadmap in dedicated 90-minute session with customer technical team. (2) VP Sales to schedule dinner with CFO to discuss partnership vision and commercial framework. (3) Provide written executive commitment letter signed by our CEO addressing reliability investment. (4) Offer board-ready materials: reliability metrics, investment summary, roadmap timeline. (5) Propose Customer Advisory Board seat. Revenue at risk: $4.2M ARR. This is our highest-value account in West region. Probability of renewal with executive engagement: 70%. Current trajectory without intervention: 45%.'),

('DOC-052', 'Exec Escalation', 'ESCALATION: West Enterprise Portfolio Risk - CRO Strategic Review', 'West', 'Enterprise', 'ALL ACCOUNTS',
 '2026-06-14',
 'EXECUTIVE ESCALATION - PORTFOLIO LEVEL. To: CRO, CFO, VP Sales West, VP Customer Success. Subject: West Enterprise renewal portfolio at elevated risk following INC-0001. Summary: INC-0001 has created systemic renewal risk across the West Enterprise segment. Key metrics: Total West Enterprise ARR: $89.4M. Accounts with renewal risk >70: 241 accounts representing $52.3M ARR. Accounts with renewal in next 120 days and risk >75: 47 accounts representing $31.2M ARR. Estimated revenue at risk (probability-weighted): $14.8M. Immediate churn threats (renewal <60 days, risk >85): TechNova Solutions ($2.8M, Jul 31), NovaPay Financial ($3.6M, Jul 15), Acme Financial Services ($4.2M, Aug 15). Recommended strategic actions: (1) Declare "West Enterprise Save Sprint" - dedicate executive team capacity for 90 days. (2) Allocate $2.1M in SLA credits and commercial concessions budget. (3) Accelerate reliability roadmap deliverables for West region. (4) Assign named executive sponsor to every account >$2M with risk >80. (5) Weekly CRO review of save progress. (6) Authorize dedicated compute for top-10 accounts at risk. If executed immediately, projected save rate: 72% of at-risk ARR. Delay of 2+ weeks reduces projected save rate to 58%.'),

('DOC-053', 'Exec Escalation', 'ESCALATION: Redwood Capital Management - Legal Threat', 'West', 'Enterprise', 'Redwood Capital Management',
 '2026-06-16',
 'EXECUTIVE ESCALATION. Account: Redwood Capital Management. ARR: $2.9M. Renewal Date: 2026-09-01. Escalation Reason: Customer legal counsel has sent formal letter demanding: (1) Full forensic data integrity audit for all customer data during INC-0001 window, (2) Written guarantee that no data was corrupted, modified, or lost, (3) Independent third-party verification. Context: Customer initially found 47 NULL values in pricing table after INC-0001. Joint investigation confirmed NULLs pre-date incident (upstream data quality issue). Customer acknowledged this but legal team is using it as basis for broader data integrity demand. Risk: If not handled carefully, could escalate to formal legal claim or regulatory complaint. Recommended approach: (1) Our General Counsel to respond to customer legal team within 48 hours. (2) Offer independent third-party audit at our cost (estimated $150K). (3) Provide formal written data integrity attestation from VP Engineering. (4) Schedule executive call (our CLO + their GC) to de-escalate. (5) Separate legal track from renewal track - do not let legal team drive renewal discussion. Renewal risk: 74/100. Legal risk: MEDIUM-HIGH.'),

('DOC-054', 'Exec Escalation', 'ESCALATION: Summit Analytics Group - Competitive Win-Back Attempt', 'West', 'Enterprise', 'Summit Analytics Group',
 '2026-06-20',
 'EXECUTIVE ESCALATION. Account: Summit Analytics Group. ARR: $2.1M. Renewal Date: 2026-08-20. Escalation Reason: Competitor has offered free 6-month pilot with full migration support, directly referencing INC-0001 in their pitch deck to the customer. Customer shared the competitor deck with their account executive (positive signal - indicates desire to stay if we match). Competitor is offering: free migration, 99.99% SLA, 20% below our pricing, dedicated success team. Recommended response: (1) Do NOT match on price - compete on value, integration depth, and switching cost reality. (2) Present honest migration cost analysis: estimated $400K in labor + 4 months of parallel running + business risk during transition. (3) Offer 2-year renewal at 10% discount with enhanced SLA and dedicated support. (4) VP Engineering to present 30-day reliability data showing post-INC-0001 improvements. (5) Emphasize: customer has 3 years of optimized workloads, trained team of 45 users, and 12 integrated applications. Switching is not free. Revenue at risk: $2.1M.'),

-- ============================================================================
-- ADDITIONAL WEST ENTERPRISE DOCS
-- ============================================================================
('DOC-060', 'Support Case Note', 'CASE-89150: AlpineView Tech - Backup Validation Request Post INC-0001', 'West', 'Enterprise', 'AlpineView Tech',
 '2026-06-15',
 'Customer: AlpineView Tech. Case opened by VP Infrastructure. Issue: Following INC-0001, customer requesting validation that their Time Travel and Fail-safe data protection layers were unaffected during the incident. Specifically want confirmation that point-in-time recovery to any timestamp during the incident window would produce complete and accurate results. Engineering confirmed all Time Travel data intact - no storage-layer corruption occurred during INC-0001 (compute layer was affected, not storage). Customer satisfied with technical explanation but requesting formal written attestation for their board. Contract: $1.6M ARR, renewal 2026-11-01. Renewal risk: 68/100.'),

('DOC-061', 'Support Case Note', 'CASE-89178: GoldCoast Media - Real-time Dashboard Outage Impact', 'West', 'Enterprise', 'GoldCoast Media',
 '2026-06-14',
 'Customer: GoldCoast Media. Case opened by Director of Ad Operations. Issue: INC-0001 caused their real-time advertising performance dashboard to go dark for 6+ hours during a major campaign launch for their largest advertiser ($50M campaign). Customer could not provide real-time performance data to advertiser, resulting in a formal complaint and potential $2M revenue clawback from the advertiser. Customer states: "Your outage directly cost us money. Not just inconvenience - actual revenue loss." Requesting: (1) SLA credits, (2) formal letter explaining the outage for their advertiser, (3) guaranteed uptime commitment for future campaign windows. Contract: $1.3M ARR, renewal 2026-10-01. Renewal risk: 82/100. Note: Revenue impact to customer ($2M) exceeds their contract value with us, creating disproportionate frustration.'),

('DOC-062', 'QBR Call Summary', 'Q2 QBR: Sierra Manufacturing - Perception Management', 'West', 'Enterprise', 'Sierra Manufacturing',
 '2026-06-22',
 'Q2 2026 QBR with Sierra Manufacturing. Attendees: Customer - IT Director, Plant Operations Manager; Internal - Account Executive, Customer Success Manager. Context: Customer experiencing unrelated connectivity issues (CASE-88902) that they attribute to INC-0001. Meeting purpose: separate fact from perception and rebuild confidence. Key outcomes: (1) Presented detailed telemetry showing customer workloads running at normal performance since INC-0001 recovery. (2) Demonstrated that connectivity drops are originating from customer network (provided packet trace evidence). (3) Customer acknowledged network issue is on their side but stated: "Even if this one is us, INC-0001 showed us that we are vulnerable to your outages. We need a DR plan." (4) Agreed to joint DR planning session. (5) Renewal sentiment: customer will renew but using INC-0001 as leverage for 8% discount. Renewal probability: 82%. Contract: $1.4M ARR.'),

('DOC-063', 'QBR Call Summary', 'Q2 QBR: Velocity Logistics - Contract Penalty Resolution', 'West', 'Enterprise', 'Velocity Logistics',
 '2026-06-23',
 'Q2 2026 QBR with Velocity Logistics. Attendees: Customer - VP Technology, Legal Director, Procurement Manager; Internal - Account Executive, Deal Desk, Legal. Focus: Resolving contractual penalty clause triggered by INC-0001. Key discussion: (1) Customer contract has non-standard clause: <99.9% monthly uptime triggers automatic 15% discount on next renewal. May uptime: 99.87% per customer measurement. (2) Our legal team confirmed clause is valid and enforceable. (3) Negotiation: Offered alternative - instead of 15% discount ($375K/year reduction), proposed: $200K immediate credit + enhanced SLA + dedicated support for 12 months. Customer legal team to review. (4) Customer VP Technology stated: "The penalty clause exists for exactly this reason. We are not trying to extract value - we are trying to ensure you take our uptime seriously." (5) Positive note: Customer confirmed they plan to renew regardless of penalty resolution. Issue is commercial terms, not churn risk. Renewal probability: 90% (terms TBD). Contract: $2.5M ARR, renewal 2026-10-01.'),

('DOC-064', 'Incident Postmortem', 'INC-0001 Financial Impact Summary: West Enterprise Revenue at Risk', 'West', 'Enterprise', 'ALL ACCOUNTS',
 '2026-06-20',
 'INC-0001 Financial Impact Assessment - Final. Prepared for CRO and CFO review. Direct financial impacts: (1) SLA credits issued/approved: $2.14M across 89 Severity 1 accounts. (2) Contractual penalty clauses triggered: 3 accounts, estimated $680K annual revenue reduction. (3) Competitive displacement threats: 4 accounts confirmed receiving proposals, $11.5M combined ARR. (4) Discount requests citing INC-0001: 12 accounts requesting avg 10% discount, potential $3.2M annual impact. (5) Expansion deals paused: 6 accounts have frozen expansion discussions pending reliability review, $4.8M pipeline at risk. Total quantified revenue impact: Immediate (credits + penalties): $2.82M one-time. Recurring (discounts + churn risk): $14.8M probability-weighted ARR at risk. Expansion pipeline frozen: $4.8M. Renewal risk concentration: 47 accounts renewing within 120 days with risk >75. Highest-value at-risk renewals: Acme Financial ($4.2M, Aug), NovaPay Financial ($3.6M, Jul), TechNova Solutions ($2.8M, Jul), Western Digital Analytics ($2.4M, Aug), Summit Analytics ($2.1M, Aug). Recommended reserve: $8.2M against potential churn and concessions.'),

-- More East/Central/South for diversity
('DOC-065', 'QBR Call Summary', 'Q2 QBR: Southeastern Data Co-op - Expansion Planning', 'South', 'Enterprise', 'Southeastern Data Co-op',
 '2026-06-18',
 'Q2 2026 QBR with Southeastern Data Co-op. Excellent meeting - customer unaffected by INC-0001 (South region). Planning 3x expansion for new analytics use cases. Currently $900K ARR with $1.5M expansion pipeline. Renewal risk: 12/100. Account health: GREEN. Customer specifically praised platform reliability as key differentiator vs competitor they evaluated last year.'),

('DOC-066', 'Support Case Note', 'CASE-89400: Heartland Financial Group - Feature Request', 'Central', 'Mid-Market', 'Heartland Financial Group',
 '2026-06-19',
 'Customer: Heartland Financial Group. Case opened by Analytics Manager. Issue: Feature request for native dbt integration in their environment. Not a support issue - routing to product team. Customer very satisfied with platform, no reliability concerns. Account health: GREEN. Renewal risk: 8/100. Contract: $180K ARR, renewal 2026-12-15.'),

('DOC-067', 'Support Case Note', 'CASE-89423: Metro Retail Solutions - Seasonal Scaling', 'East', 'Mid-Market', 'Metro Retail Solutions',
 '2026-06-20',
 'Customer: Metro Retail Solutions. Case opened by Data Team Lead. Issue: Pre-planning for Black Friday peak load (6 months out). Customer wanting to understand auto-scaling options and cost projections. Proactive engagement, no current issues. Account health: GREEN. Renewal risk: 14/100. Contract: $210K ARR, renewal 2026-11-01.'),

('DOC-068', 'Renewal Playbook', 'Save Play: Customer Advisory Board Invitation for Strategic Accounts', 'West', 'Enterprise', 'ALL ACCOUNTS',
 '2026-06-15',
 'RENEWAL PLAYBOOK: Customer Advisory Board (CAB) Invitation. Strategy: Invite at-risk West Enterprise accounts to join a newly formed Customer Advisory Board focused on platform reliability. Purpose: (1) Demonstrate that customer voice directly influences product roadmap. (2) Create executive-level engagement touchpoint beyond commercial relationship. (3) Build community among customers with shared reliability concerns - they reassure each other once improvements are visible. (4) Provide early access to new reliability features, creating switching cost. Target candidates: Top 10 West Enterprise accounts by ARR with renewal risk >70. Specifically: Acme Financial Services, TechNova Solutions, Pacific Mutual Insurance, NovaPay Financial, Western Digital Analytics, Redwood Capital Management, Summit Analytics Group, Velocity Logistics, Pinnacle Biotech, Cascade Health Systems. Offer: quarterly in-person meetings (hosted at our HQ), direct access to VP Engineering and CTO, input on reliability roadmap prioritization, first access to new infrastructure options. Budget: $200K annually for events and travel. Expected ROI: retaining even 2 of the top-10 accounts covers 5+ years of CAB costs.'),

('DOC-069', 'Exec Escalation', 'ESCALATION: NovaPay Financial - Renewal in 2 Days, Dedicated Compute Delivery', 'West', 'Enterprise', 'NovaPay Financial',
 '2026-06-13',
 'EXECUTIVE ESCALATION - CRITICAL TIMELINE. Account: NovaPay Financial. ARR: $3.6M. Renewal Date: 2026-07-15 (2 DAYS from this writing). Status: Customer gave verbal commitment to renew IF dedicated compute cluster is operational by renewal date. Engineering status: Cluster provisioned and tested. Migration of customer transaction workloads scheduled for 2026-07-14 (tomorrow). Risk: Any delay in migration could jeopardize the renewal. Action required: VP Engineering to personally confirm migration readiness. Customer Success to schedule go-live confirmation call with customer COO for 2026-07-14 EOD. Fallback: If migration encounters issues, immediately offer 30-day renewal extension at current terms while completing migration. Do NOT let the renewal lapse. Revenue at risk: $3.6M ARR. Renewal probability with on-time delivery: 90%. Without: 55%.'),

('DOC-070', 'Support Case Note', 'CASE-89500: BrightPath Education - Query Performance After INC-0001', 'West', 'Enterprise', 'BrightPath Education',
 '2026-06-16',
 'Customer: BrightPath Education. Case opened by Director of Institutional Research. Issue: Customer reports 25% increase in query execution times for their student analytics workloads since INC-0001. Investigation: confirmed 15% increase due to storage rebalancing (temporary, resolving within 1 week) and 10% due to 40% increase in data volume from new semester enrollment data. Customer satisfied with explanation after technical deep-dive. Requesting notification when storage rebalancing is complete. Account health: YELLOW (moved from GREEN post INC-0001). Contract: $980K ARR, renewal 2026-12-01. Renewal risk: 62/100.'),

('DOC-071', 'QBR Call Summary', 'Q2 QBR: GoldCoast Media - Advertiser SLA Discussion', 'West', 'Enterprise', 'GoldCoast Media',
 '2026-06-24',
 'Q2 2026 QBR with GoldCoast Media. Attendees: Customer - Director Ad Operations, CFO, Head of Engineering; Internal - Account Executive, Customer Success Manager, Solutions Architect. Critical meeting focused on $2M advertiser revenue clawback risk from INC-0001. Key outcomes: (1) Customer presented timeline showing their advertiser complaint and revenue risk. (2) We offered to provide formal incident documentation and reliability commitments that GoldCoast can share with their advertiser. (3) Customer requests: real-time SLA dashboard they can embed in their advertiser-facing portal, guaranteed campaign-window protection (no maintenance during declared campaign periods), and immediate notification (<2 min) of any service degradation. (4) Commercial ask: 20% discount on renewal citing $2M business impact. (5) Customer will not churn (strong technical fit) but will aggressively negotiate on price. Renewal probability: 75% at current terms, 95% with concessions. Contract: $1.3M ARR, renewal 2026-10-01. Renewal risk: 82/100.'),

('DOC-072', 'Support Case Note', 'CASE-89534: Pacific Mutual Insurance - Query Compilation Latency Update', 'West', 'Enterprise', 'Pacific Mutual Insurance',
 '2026-06-18',
 'Customer: Pacific Mutual Insurance. Follow-up to CASE-88745. Issue: Customer query compilation latency investigation complete. Findings: 2-3x compilation time increase during 8-10am window is caused by concurrent DDL operations from their new data pipeline (running CREATE OR REPLACE TABLE 400+ times per hour during that window). Recommended: switch to INSERT OVERWRITE pattern to eliminate DDL overhead. Customer engineering team implementing fix. Note: Customer initially attributed this to INC-0001 residual impact. After technical explanation, customer acknowledged this is organic growth issue unrelated to the incident. CIO appreciated transparent investigation. Positive interaction that slightly reduces renewal tension. Updated renewal risk: 84/100 (down from 87).'),

('DOC-073', 'Renewal Playbook', 'Save Play: 90-Day Reliability Proof Program', 'West', 'Enterprise', 'ALL ACCOUNTS',
 '2026-06-18',
 'RENEWAL PLAYBOOK: 90-Day Reliability Proof Program. Purpose: For accounts where renewal decision hinges on demonstrated reliability improvement, offer a structured 90-day proof program with measurable outcomes. Structure: (1) Day 1-7: Deploy enhanced monitoring on customer workloads with customer-visible dashboard showing real-time uptime, latency p50/p95/p99, error rates. (2) Day 1-30: Weekly reliability report emailed to customer executive sponsor showing all metrics trending. (3) Day 30: First checkpoint - present 30-day reliability data. Target: 99.99%+ uptime, <100ms p95 latency, <0.01% error rate. (4) Day 31-60: Conduct chaos engineering exercise (controlled failover test) with customer observation. Demonstrate recovery in <2 minutes. (5) Day 60: Second checkpoint - present 60-day data plus chaos test results. (6) Day 61-90: Customer validates via their own monitoring that metrics are sustained. (7) Day 90: Final review - data-driven renewal conversation. Target accounts: Any West Enterprise account with renewal >60 days out and risk 70-85. Accounts with <60 days need faster intervention (see Executive Escalation playbook). Expected impact: 40% reduction in renewal risk score for participating accounts.'),

('DOC-074', 'Support Case Note', 'CASE-89567: Frontier Analytics - New Deployment West Region Concerns', 'West', 'Mid-Market', 'Frontier Analytics',
 '2026-06-20',
 'Customer: Frontier Analytics. New customer (signed 3 months ago). Case opened by CTO. Issue: Customer heard about INC-0001 through industry contacts and is concerned about their recent decision to deploy in West region. Requesting: (1) confirmation their account is on new infrastructure (post-remediation), (2) details of reliability improvements implemented. Note: This is a perception issue from a NEW customer - they were not affected by INC-0001 but are worried about future risk. Provided comprehensive briefing on post-incident improvements. Customer satisfied. Contract: $340K ARR (new). Account health: GREEN. No renewal risk (new contract). Important context: new customer acquisition in West region may be impacted by INC-0001 reputation if not proactively addressed.'),

('DOC-075', 'Exec Escalation', 'ESCALATION: Portfolio Update - West Enterprise Save Sprint Week 2 Results', 'West', 'Enterprise', 'ALL ACCOUNTS',
 '2026-06-28',
 'EXECUTIVE UPDATE: West Enterprise Save Sprint - Week 2 Progress. To: CRO, VP Sales West, VP Customer Success. Results: (1) Executive outreach completed to 15 of 18 targeted accounts (>$2M ARR, risk >80). (2) NovaPay Financial: Dedicated compute delivered on time, renewal SIGNED for 2 years at $3.6M ARR (SAVE). (3) Acme Financial Services: VP Engineering reliability presentation delivered. CFO described it as "credible and detailed." Board presentation materials provided. Awaiting board meeting outcome (July). (4) TechNova Solutions: CRO call completed. Customer agreed to pause competitive evaluation for 30 days pending our custom reliability proposal delivery (due 2026-07-05). (5) Pacific Mutual Insurance: Positive trajectory - CIO attended reliability roadmap session, described it as "the level of transparency we needed." (6) Credits/concessions approved: $1.8M of $2.1M budget deployed. (7) Remaining urgent actions: Western Digital Analytics multi-AZ migration (in progress), Summit Analytics competitive defense package (in preparation), GoldCoast Media commercial proposal (in review). Summary: Of $14.8M probability-weighted ARR at risk, we have secured $3.6M (NovaPay) and moved $7.2M from HIGH to MEDIUM risk. $4.0M remains HIGH risk. Next update: Week 3.'),

-- Additional rows for volume and diversity
('DOC-076', 'Support Case Note', 'CASE-89600: CloudFirst Startup - Onboarding Assistance', 'East', 'SMB', 'CloudFirst Startup',
 '2026-06-22',
 'Customer: CloudFirst Startup. New SMB customer needing onboarding assistance with data loading from S3. Standard onboarding, no issues. Account health: GREEN. Contract: $36K ARR.'),

('DOC-077', 'Support Case Note', 'CASE-89634: Continental Supply Chain - Warehouse Optimization', 'Central', 'Enterprise', 'Continental Supply Chain',
 '2026-06-23',
 'Customer: Continental Supply Chain. Routine warehouse sizing optimization. Customer running XLARGE warehouse for workloads that could run on MEDIUM with multi-cluster. Saving them $40K/month with configuration change. Very satisfied. Account health: GREEN. Renewal risk: 15/100. Contract: $1.2M ARR, Central region - no INC-0001 impact.'),

('DOC-078', 'QBR Call Summary', 'Q2 QBR: MidStates Energy Corp - IoT Expansion Discussion', 'Central', 'Enterprise', 'MidStates Energy Corp',
 '2026-06-25',
 'Q2 2026 QBR with MidStates Energy Corp. Positive meeting focused on expansion. Customer wants to bring 500M IoT sensor records/day onto platform for predictive maintenance analytics. Discussing Snowpipe Streaming for real-time ingestion. No reliability concerns (Central region, unaffected by INC-0001). Expansion pipeline: $800K. Current: $1.5M ARR. Renewal risk: 31/100 (cost sensitivity only, not reliability). Account health: GREEN.'),

('DOC-079', 'Support Case Note', 'CASE-89700: AlpineView Tech - DR Planning Engagement', 'West', 'Enterprise', 'AlpineView Tech',
 '2026-06-25',
 'Customer: AlpineView Tech. Follow-up engagement post CASE-89150. Customer board has approved budget for disaster recovery planning project. They want to implement cross-region replication to East as a backup for West region workloads. Professional services engagement scoped at 120 hours. Positive outcome: INC-0001 concern converted into expansion opportunity ($180K professional services + estimated $400K additional compute for DR environment). Customer attitude shifted from fearful to proactive. Account health improving: YELLOW trending GREEN. Renewal risk: 58/100 (down from 68).'),

('DOC-080', 'Incident Postmortem', 'INC-0001 Lessons Learned: Platform Engineering Retrospective', 'West', 'Enterprise', 'ALL ACCOUNTS',
 '2026-06-30',
 'INC-0001 Platform Engineering Retrospective - Final. Key lessons: (1) Change freeze policies must exempt critical reliability patches. The firmware fix was available 2 weeks before the incident but deployment was blocked by month-end change freeze. New policy: reliability and security patches are exempt from change freezes with VP Engineering approval. (2) Blast radius management: Rack affinity rules allowed multiple high-value tenants to co-locate on adjacent racks. New requirement: accounts >$1M ARR must be distributed across minimum 3 rack groups. (3) Thermal monitoring gaps: Existing alerts triggered at 75C (too late). New threshold: automated workload migration at 68C, alert at 65C. (4) Failover speed: Current failover to secondary storage took 2+ hours. Investment approved for synchronous replication enabling <2 minute failover (target: Q4 delivery). (5) Customer communication: First customer notification was 43 minutes after incident declaration. New target: <15 minutes. Automated status page update pipeline deployed. (6) Recovery validation: Snowpipe streams did not auto-resume for some customers. Fix deployed: automated stream health check and restart 5 minutes after service restoration confirmed. Total engineering investment in reliability improvements: $12M allocated for FY2027.');
